name = "notero-download"
main = "src/worker.ts"
compatibility_date = "2024-09-25"
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "download.notero.vanoni.dev"
custom_domain = true
